### ISSUE TITLE
Have (Warlpiri) preverb list test match against composed entries

### ISSUE THREAD

**Issue by manning** [CoEDL/yinarlingi#2]
It would be great to broaden the preverb cross-reference check to check for composed entries. That is, it would just be good and correct, and cut down the number of things to fix, if for a \pvl item A in entry B, if there is an entry of either

	A + B
	A + “-“ + B

then that isn’t an error.

So, for example, in:

	\me paji-rni*2* (V):

item

	\pvl … maarn-

shouldn’t be an error, because there is an entry: 

	\me maarn-paji-rni (V): (Y)

I’m hoping that wouldn’t be difficult to add….

**Comment by fauxneticien** [comment]
I've added these 'full forms' to the whitelist. The failing list didn't go down by much, though.

<img width="332" alt="screen shot 2018-10-07 at 10 18 01 am" src="https://user-images.githubusercontent.com/9938298/46584613-4f1c1100-ca1a-11e8-88e9-c60a3ed4fae2.png">

**Comment by manning** [comment]
We discussed IRL that the problem is that the pre-composed forms are actually already in the whitelist, and rather what is needed is to test the composed form A + B against the whitelist....

**Comment by fauxneticien** [comment]
@manning 

As expected from IRL tests, 'yapiti' and 'kilwirri' have disappeared from the error list because they can be found in 'yapiti-nya-nyi' and 'kilwirri-nyina-mi', respectively. 

![screen shot 2018-10-17 at 2 57 39 pm](https://user-images.githubusercontent.com/9938298/47118761-392dfd80-d21d-11e8-9530-96bf19cdc644.png)

**Comment by manning** [comment]
Thanks for working on this – and the number is going down, now!!!

However, sorry to be a pain in the rear, but I still think that there's some that I can be fussy on. :(

In entry \me paji-rni*2* (V): for

\pvl jamulu*1*, kajurr-, larra, luwirr-, maarn-, miti, murruly-, …

**maarn-** is still unmatched but there is an entry:

\me maarn-paji-rni (V): (Y)

Is it maybe not matching because the "*2*" is still on the verb?  Or ....?

And then for:

45227 | \pvl jiily-, junpurr(pa), jurnj	... | waa-karlikarli-

I changed the \pvl entry to add a hyphen waa-karlikarli- rather than waakarlikarli but it still wouldn't match up with:

\sse waa-karlikarli-ma-ni (V): (La)

I tried it in the \pvl as both 

    waa-karlikarli-
    waa-karlikarli

Neither matched.....

**Comment by fauxneticien** [comment]
> However, sorry to be a pain in the rear, but I still think that there's some that I can be fussy on. :(

No worries—totally fine! I can't do both detective groundwork and implement code at the moment, so I'm happy to be pointed to things to implement.

> Is it maybe not matching because the "2" is still on the verb

Yes it was—I forgot to strip homophones in the A + B form 😅

Error list down to 18 now: http://warlpiri-tests.netlify.com/#test_pvl_fuzzy_homed

> I changed the \pvl entry to add a hyphen waa-karlikarli- rather than waakarlikarli but it still wouldn't match up with:
> 
> \sse waa-karlikarli-ma-ni (V): (La)

Hm, this seem to have fixed itself?

Attached is the latest error list before it gets aggregated. If your pattern-matching eagle eyes spot some more easy gains, happy to write the code to account for them (uh, in .txt form to cheat GitHub attachment restrictions).

[pvl_fuzzy_derivations.csv.txt](https://github.com/CoEDL/yinarlingi/files/2494567/pvl_fuzzy_derivations.csv.txt)

**Comment by manning** [comment]
Thanks a lot! I think we're good now, and the remaining work is more substantive!
